<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MSI" ignored="0" name="Test" tests="6" failures="3" timestamp="14 Aug 2021 05:43:09 GMT" time="0.077" errors="0">
  <testcase name="checkTestOne" time="0.016" classname="testNgCases.Login">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at testNgCases.Login.checkTestOne(Login.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkTestOne -->
  <testcase name="checkTestThree" time="0.001" classname="testNgCases.Login"/>
  <testcase name="checkTestTwo" time="0.003" classname="testNgCases.Login">
    <failure type="java.lang.AssertionError" message="expected [5] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [4]
	at testNgCases.Login.checkTestTwo(Login.java:14)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkTestTwo -->
  <testcase name="CheckTestOne" time="0.003" classname="testNgCases.SignIn">
    <failure type="java.lang.AssertionError" message="expected [1] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [3]
	at testNgCases.SignIn.CheckTestOne(SignIn.java:9)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- CheckTestOne -->
  <testcase name="CheckTestThree" time="0.004" classname="testNgCases.SignIn"/>
  <testcase name="CheckTestTow" time="0.001" classname="testNgCases.SignIn"/>
</testsuite> <!-- Test -->
