<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="offlinewebsite.OperatorPage" tests="1" time="0.254" ignored="4" failures="1" timestamp="26 Oct 2021 08:49:42 GMT" skipped="0" hostname="MSI" errors="0">
  <testcase name="checkOperatorTable" time="0.254" classname="offlinewebsite.OperatorPage">
    <failure type="java.lang.AssertionError" message="lists don&#039;t have the same size expected [42] but found [1]">
      <![CDATA[java.lang.AssertionError: lists don't have the same size expected [42] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:556)
	at org.testng.Assert.assertEquals(Assert.java:533)
	at offlinewebsite.OperatorPage.checkOperatorTable(OperatorPage.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- checkOperatorTable -->
  <testcase name="checkTiming" classname="offlinewebsite.OperatorPage">
    <skipped/>
  </testcase> <!-- checkTiming -->
  <testcase name="test" classname="offlinewebsite.OperatorPage">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="checkTechnicalPerson" classname="offlinewebsite.OperatorPage">
    <skipped/>
  </testcase> <!-- checkTechnicalPerson -->
  <testcase name="checkOperatorOnWhatsapp" classname="offlinewebsite.OperatorPage">
    <skipped/>
  </testcase> <!-- checkOperatorOnWhatsapp -->
</testsuite> <!-- offlinewebsite.OperatorPage -->
